- hosts: all
  become: yes
  vars_prompt: 
    - name: php_version
      prompt: "Specify PHP Version"
      default: 7.4

    - name: node_version
      prompt: "Specify Node version"
      default: 14  

  tasks:
    - debug:
        msg: Basic requirement packages for all hosts
    - include: basic/basic_dependencies.yml
    - include: chrome/chrome.yml
    - include: dbeaver/dbeaver.yml
    - include: skype/skype.yml
    - include: docker/docker.yml
    - include: postman/postman.yml
    - include: tableplus/tableplus.yml
    - include: teams/teams.yml
    - include: vscode/vscode.yml

- hosts: phpteam
  become: yes
  tasks:
    - debug:
        msg: PHP-Team
    - include: node/node.yml

- hosts: nodeteam
  become: yes
  tasks:
    - debug:
        msg: Node-Team
    - include: php/php.yml

- hosts: testsystem
  become: yes
  tasks:
    - debug:
        msg: Test-System
    - include: php/php.yml
    - include: node/node.yml