---
- name: Add Docker Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding Docker Repo
  apt_repository:
    # repo: deb https://download.docker.com/linux/ubuntu bionic stable
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    filename: docker-stable

- name: Installing Docker
  apt: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
    force_apt_get: yes
    update_cache: yes